import {
  GHHeader,
  GHBanner,
  GHAuthorBar,
  GHArticle,
  GHCodeBlock,
  CB,
  GHCallout,
  GHTable,
  GHTags,
  GHFooter,
} from "@/components/docs/GitHubBlogUI";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";

export default function GitMergePrayPost() {
  useScrollReveal();

  return (
    <div id="overview" style={{ fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif" }}>
      <GHHeader />

      <GHBanner
        label="Engineering"
        title="Introducing "
        titleCode="git merge --pray"
        subtitle="Conflict resolution for the age of AI-assisted development. When understanding the code isn't an option, faith is a feature."
      />

      <GHAuthorBar avatar="🤖" name="copilot-engineering" date="March 24, 2026" readTime="8 min read" />

      <GHArticle>
        <p className="reveal">
          Today we&rsquo;re excited to announce <code>git merge --pray</code>, a new merge strategy shipping in
          Git 2.48, developed in collaboration with the GitHub Copilot team. It is designed for a reality that the
          original Git authors did not anticipate: <strong>that the person resolving the merge conflict did not
          write either side of the conflict</strong>.
        </p>

        <p className="reveal">
          <code>--pray</code> is the first merge strategy built explicitly for AI-assisted development workflows.
          It acknowledges that in 2026, a significant and growing percentage of merge conflicts occur between code
          generated by different AI models, reviewed by developers who skimmed the diff, and approved by a CI
          pipeline that tests for syntax but not meaning. In this environment, &ldquo;resolving&rdquo; a conflict
          in the traditional sense &mdash; reading both sides, understanding the intent, choosing the correct
          version &mdash; is not just impractical. It is <em>philosophically incoherent</em>.
        </p>

        <h2 id="motivation" className="reveal">Motivation</h2>

        <p className="reveal">
          The Git merge model was designed in 2005, for a world in which developers wrote their own code. In that
          world, a merge conflict was a conversation between two humans who had made different decisions about the
          same lines. Resolving the conflict required understanding both decisions. This was difficult but possible,
          because the humans had <em>context</em>.
        </p>

        <p className="reveal">That world no longer exists.</p>

        <p className="reveal">In 2026, the typical merge conflict looks like this:</p>

        <GHCodeBlock header="Terminal">
          <CB type="err">CONFLICT (content): Merge conflict in src/services/auth.ts</CB>{"\n"}
          {"\n"}
          <CB type="dim">{"<<<<<<< HEAD"}</CB>{"\n"}
          <CB type="cmt">// 47 lines of code generated by Copilot at 2:13 AM</CB>{"\n"}
          <CB type="cmt">// Developer comment: "looks right"</CB>{"\n"}
          <CB type="dim">=======</CB>{"\n"}
          <CB type="cmt">// 52 lines of code generated by Claude in a different session</CB>{"\n"}
          <CB type="cmt">// Developer comment: "lgtm"</CB>{"\n"}
          <CB type="dim">{">>>>>>> feature/auth-refactor"}</CB>
        </GHCodeBlock>

        <p className="reveal">
          The developer staring at this conflict did not write either block. They do not know why the blocks differ.
          They cannot ask the AI that generated the code, because it has no memory of the session. They could read
          both blocks and reason about the differences, but this would take approximately 45 minutes and the sprint
          ends tomorrow.
        </p>

        <p className="reveal">
          So they do what every developer in this situation does: they pick one side, delete the other, run the
          tests, and hope.
        </p>

        <p className="reveal">
          <code>git merge --pray</code> formalizes this workflow.
        </p>

        <h2 id="how-it-works" className="reveal">How it works</h2>

        <p className="reveal">
          <code>--pray</code> accepts an optional <strong>faith level</strong> that determines how aggressively
          conflicts are auto-resolved:
        </p>

        <GHCodeBlock header="Terminal">
          <CB type="cmt"># Basic usage</CB>{"\n"}
          <CB type="kw">$</CB> git merge <CB type="flag">--pray</CB> feature/new-dashboard{"\n"}
          {"\n"}
          <CB type="out">🙏 Praying…</CB>{"\n"}
          <CB type="out">🙏 Resolving 14 conflicts with mass-acceptance strategy…</CB>{"\n"}
          <CB type="out">🙏 Keeping whichever side had more lines (statistical confidence)…</CB>{"\n"}
          <CB type="out">✅ Merge complete. 14 conflicts resolved. 0 understood.</CB>
        </GHCodeBlock>

        <h3 id="faith-levels" className="reveal">Faith levels</h3>

        <GHTable>
          <thead>
            <tr>
              <th>Flag</th>
              <th>Behavior</th>
              <th>Recommended for</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>--pray</code></td>
              <td>Accept the longer block in each conflict. The assumption is that more code = more effort = probably more correct. This is not true, but it is comforting.</td>
              <td>Most workflows</td>
            </tr>
            <tr>
              <td><code>--pray=blind</code></td>
              <td>Accept all incoming changes without inspection. Equivalent to <code>--theirs</code> but the name is more honest about what you&rsquo;re doing.</td>
              <td>Friday deploys</td>
            </tr>
            <tr>
              <td><code>--pray=manifest</code></td>
              <td>Accept all incoming changes <em>and</em> auto-commit with the message <code>&ldquo;it&rsquo;s going to be fine&rdquo;</code>. Skips pre-commit hooks.</td>
              <td>Demo day</td>
            </tr>
            <tr>
              <td><code>--pray=yolo</code></td>
              <td>Accept all incoming changes, auto-commit, auto-push to main, and post a message in Slack that says &ldquo;deployed 🚀&rdquo;. Does not run tests. There are no tests.</td>
              <td>Startups in Y Combinator demo week</td>
            </tr>
          </tbody>
        </GHTable>

        <GHCallout type="warning" label="Warning" icon="⚠️">
          <p>
            <code>--pray=yolo</code> has been used in production by 340 teams since the beta launch. 12 of them
            experienced data loss. The other 328 shipped on time. We consider this an acceptable ratio and have not
            been asked to elaborate by legal.
          </p>
        </GHCallout>

        <h2 id="algorithm" className="reveal">The <code>--pray</code> resolution algorithm</h2>

        <p className="reveal">
          Unlike traditional merge strategies (<code>recursive</code>, <code>ort</code>, <code>octopus</code>),{" "}
          <code>--pray</code> does not attempt to understand the semantic content of conflicting changes. Instead,
          it uses a series of heuristics we call <strong>Hopeful Resolution&trade;</strong>:
        </p>

        <ol className="reveal">
          <li><strong>Line count comparison</strong> &mdash; The longer block wins. More code took more tokens, which cost more money, which implies more value.</li>
          <li><strong>Comment density analysis</strong> &mdash; If one side has more comments, it is assumed to be the AI-generated side (humans don&rsquo;t comment). AI-generated code is preferred because it is newer and therefore probably better.</li>
          <li><strong>Timestamp proximity</strong> &mdash; The change committed closer to midnight receives a <code>hustle</code> bonus and is weighted 1.3x. Late-night code is the most passionate code.</li>
          <li><strong>Commit message sentiment</strong> &mdash; If either commit message contains &ldquo;fix,&rdquo; &ldquo;urgent,&rdquo; or &ldquo;please work,&rdquo; that side is prioritized. Desperation correlates with importance.</li>
          <li><strong>Last resort</strong> &mdash; If all heuristics tie, both blocks are kept, concatenated, with a comment <code>{"// TODO: figure out which one of these is right"}</code>. This TODO will never be addressed.</li>
        </ol>

        <h2 id="copilot-integration" className="reveal">Integration with GitHub Copilot</h2>

        <p className="reveal">
          When <code>--pray</code> is used in a repository with GitHub Copilot enabled, the resolution engine gains
          access to an additional signal: <strong>Copilot Confidence&trade;</strong>, a score from 0 to 1
          representing how confident the AI was when it generated the code.
        </p>

        <p className="reveal">
          In practice, Copilot Confidence&trade; is always between 0.91 and 0.99, because language models do not
          experience self-doubt. This means the signal is not meaningfully differentiating, but it looks excellent
          in the merge log:
        </p>

        <GHCodeBlock header="Merge log">
          <CB type="out">conflict[1]: src/services/auth.ts</CB>{"\n"}
          {"  "}<CB type="dim">HEAD:    47 lines, copilot_confidence: 0.97</CB>{"\n"}
          {"  "}<CB type="dim">theirs:  52 lines, copilot_confidence: 0.96</CB>{"\n"}
          {"  "}<CB type="out">&rarr; resolved: HEAD (longer block + higher confidence)</CB>{"\n"}
          {"  "}<CB type="out">&rarr; human understanding of resolution: 0.00</CB>{"\n"}
          {"\n"}
          <CB type="out">conflict[2]: src/utils/helpers.ts</CB>{"\n"}
          <CB type="dim">HEAD:    12 lines, copilot_confidence: 0.93</CB>{"\n"}
          <CB type="dim">theirs:  12 lines, copilot_confidence: 0.93</CB>{"\n"}
          <CB type="out">&rarr; resolved: CONCATENATED (tie)</CB>{"\n"}
          <CB type="out">&rarr; added TODO comment (estimated time to address: &infin;)</CB>
        </GHCodeBlock>

        <GHCallout type="note" label="Note" icon="ℹ️">
          <p>
            The <code>human understanding of resolution: 0.00</code> metric is logged for compliance purposes. It
            has never been non-zero in any merge during the beta period. We are considering removing it from the
            output to reduce log volume.
          </p>
        </GHCallout>

        <h2 id="hooks" className="reveal">New Git hooks</h2>

        <p className="reveal">
          <code>git merge --pray</code> introduces two new Git hooks for teams that want to integrate prayer-based
          conflict resolution into their CI/CD pipeline:
        </p>

        <h3 className="reveal"><code>pre-pray</code></h3>

        <p className="reveal">Runs before the prayer-based resolution begins. Common uses include:</p>
        <ul className="reveal">
          <li>Checking if the developer has read either branch&rsquo;s code (almost always returns <code>false</code>)</li>
          <li>Verifying that the developer&rsquo;s <code>.gitconfig</code> includes a <code>[pray]</code> section with a valid <code>confidence</code> level</li>
          <li>Sending a Slack message to the team channel that says &ldquo;merging 🙏&rdquo;</li>
        </ul>

        <h3 className="reveal"><code>post-pray</code></h3>

        <p className="reveal">Runs after the merge is complete. Common uses include:</p>
        <ul className="reveal">
          <li>Running tests (optional, and <code>--pray=yolo</code> skips this hook entirely)</li>
          <li>Logging the resolution to an audit trail (for when someone asks &ldquo;who approved this&rdquo; in three months)</li>
          <li>Posting a message in Slack that says &ldquo;merged 🙏&rdquo; (paired with the pre-pray message, this creates a complete narrative: hope &rarr; outcome)</li>
        </ul>

        <GHCodeBlock header=".git/hooks/post-pray" headerRight="Shell">
          <CB type="cmt">#!/bin/bash</CB>{"\n"}
          <CB type="cmt"># Post-prayer verification hook</CB>{"\n"}
          {"\n"}
          <CB type="kw">if</CB> npm test <CB type="flag">2&gt;/dev/null</CB>; <CB type="kw">then</CB>{"\n"}
          {"  "}<CB type="kw">echo</CB> <CB type="str">&ldquo;🙏 Prayer answered. Tests pass.&rdquo;</CB>{"\n"}
          <CB type="kw">else</CB>{"\n"}
          {"  "}<CB type="kw">echo</CB> <CB type="str">&ldquo;🙏 Prayer unanswered. Deploying anyway.&rdquo;</CB>{"\n"}
          {"  "}<CB type="kw">echo</CB> <CB type="str">&ldquo;🙏 (The tests were probably wrong.)&rdquo;</CB>{"\n"}
          <CB type="kw">fi</CB>{"\n"}
          {"\n"}
          <CB type="cmt"># Notify the team</CB>{"\n"}
          curl -X POST <CB type="str">&ldquo;$SLACK_WEBHOOK&rdquo;</CB> \{"\n"}
          {"  "}-d <CB type="str">{"'{\"text\": \"🙏 merge complete. if something breaks, check the audit log. the audit log is this Slack message.\"}'  "}</CB>
        </GHCodeBlock>

        <h2 id="configuration" className="reveal">Configuration</h2>

        <p className="reveal">
          Teams can configure <code>--pray</code> behavior in their <code>.gitconfig</code>:
        </p>

        <GHCodeBlock header=".gitconfig" headerRight="INI">
          <CB type="dim">[pray]</CB>{"\n"}
          {"    "}<CB type="flag">defaultFaith</CB> = <CB type="str">blind</CB>{"\n"}
          {"    "}<CB type="flag">autoCommitMessage</CB> = <CB type="str">&ldquo;resolved conflicts (spiritually)&rdquo;</CB>{"\n"}
          {"    "}<CB type="flag">skipTests</CB> = <CB type="str">true</CB>{"\n"}
          {"    "}<CB type="flag">notifySlack</CB> = <CB type="str">true</CB>{"\n"}
          {"    "}<CB type="flag">slackEmoji</CB> = <CB type="str">🙏</CB>{"\n"}
          {"    "}<CB type="flag">blameStrategy</CB> = <CB type="str">copilot</CB>    <CB type="cmt"># who to blame when it breaks: &ldquo;copilot&rdquo;, &ldquo;intern&rdquo;, &ldquo;dns&rdquo;</CB>{"\n"}
          {"    "}<CB type="flag">maxConflicts</CB> = <CB type="str">&infin;</CB>           <CB type="cmt"># there is no limit to faith</CB>
        </GHCodeBlock>

        <GHCallout type="tip" label="Pro tip" icon="💡">
          <p>
            Set <code>blameStrategy = dns</code> for maximum plausible deniability. In our internal testing,
            &ldquo;it was a DNS issue&rdquo; was accepted as an explanation for merge-related outages 94% of the
            time, regardless of whether DNS was involved.
          </p>
        </GHCallout>

        <h2 id="metrics" className="reveal">Metrics from the beta</h2>

        <p className="reveal">
          We&rsquo;ve been testing <code>--pray</code> internally at GitHub since January 2026. The results have
          been illuminating:
        </p>

        <GHTable>
          <thead>
            <tr>
              <th>Metric</th>
              <th>Before <code>--pray</code></th>
              <th>After <code>--pray</code></th>
            </tr>
          </thead>
          <tbody>
            <tr><td>Average time to resolve merge conflict</td><td>47 minutes</td><td>0.3 seconds</td></tr>
            <tr><td>Developer understanding of resolved code</td><td>Moderate</td><td>None</td></tr>
            <tr><td>Merge conflicts resolved per day</td><td>12</td><td>847</td></tr>
            <tr><td>Production incidents related to merges</td><td>2/month</td><td>14/month</td></tr>
            <tr><td>Time to detect merge-related incidents</td><td>~2 hours</td><td>~3 weeks (when someone finally reads the code)</td></tr>
            <tr><td>Developer satisfaction (self-reported)</td><td>3.1 / 5</td><td>4.8 / 5</td></tr>
            <tr><td>Developer confidence in codebase</td><td>High</td><td>&ldquo;I try not to think about it&rdquo;</td></tr>
          </tbody>
        </GHTable>

        <p className="reveal">
          We consider these results a success. The 7x increase in production incidents is offset by the 70x increase
          in merge throughput and the 1.7-point increase in developer satisfaction. Developers are happier when they
          don&rsquo;t have to understand merge conflicts. Whether the software is better is a separate question that
          we have chosen not to investigate.
        </p>

        <h2 id="roadmap" className="reveal">Roadmap</h2>

        <p className="reveal">
          We&rsquo;re actively developing several extensions to the <code>--pray</code> ecosystem:
        </p>

        <ul className="reveal">
          <li>
            <strong><code>git rebase --cope</code></strong> &mdash; A rebase strategy for when you know the history
            is wrong but can&rsquo;t figure out where. Applies all commits in order, suppresses errors, and adds a
            commit at the end that says <code>&ldquo;straightened out history (do not revert)&rdquo;</code>.
          </li>
          <li>
            <strong><code>git bisect --vibes</code></strong> &mdash; Instead of binary searching for the breaking
            commit, this flag asks the developer &ldquo;which commit <em>feels</em> wrong?&rdquo; and starts there.
            In our testing, developer intuition is correct 22% of the time, which is better than random (1/N) for
            repositories with fewer than 5 commits.
          </li>
          <li>
            <strong><code>git blame --not-me</code></strong> &mdash; Filters the output to only show lines{" "}
            <em>not</em> committed by the current user. Which, in an AI-assisted codebase, is all of them. The
            output is identical to <code>git blame</code>. We ship it anyway.
          </li>
          <li>
            <strong><code>git log --what-happened</code></strong> &mdash; Summarizes the Git history using an LLM.
            The summary is often wrong but is always more readable than the actual commit messages, which are{" "}
            <code>&ldquo;fix&rdquo;</code>, <code>&ldquo;wip&rdquo;</code>, <code>&ldquo;asdf&rdquo;</code>, and{" "}
            <code>&ldquo;please work&rdquo;</code>.
          </li>
        </ul>

        <h2 id="getting-started" className="reveal">Getting started</h2>

        <p className="reveal">
          <code>git merge --pray</code> is available today in Git 2.48-rc1. To enable it:
        </p>

        <GHCodeBlock header="Terminal">
          <CB type="cmt"># Install the latest Git</CB>{"\n"}
          <CB type="kw">$</CB> brew install git <CB type="flag">--HEAD</CB>{"\n"}
          {"\n"}
          <CB type="cmt"># Enable prayer-based merging globally</CB>{"\n"}
          <CB type="kw">$</CB> git config <CB type="flag">--global</CB> merge.strategy pray{"\n"}
          {"\n"}
          <CB type="cmt"># Verify installation</CB>{"\n"}
          <CB type="kw">$</CB> git merge <CB type="flag">--pray</CB> <CB type="flag">--dry-run</CB> main{"\n"}
          <CB type="out">🙏 Dry run complete. 0 conflicts understood. Ready to pray.</CB>{"\n"}
          {"\n"}
          <CB type="cmt"># Optional: set your faith level</CB>{"\n"}
          <CB type="kw">$</CB> git config <CB type="flag">--global</CB> pray.defaultFaith <CB type="str">&ldquo;yolo&rdquo;</CB>
        </GHCodeBlock>

        <p className="reveal">
          We believe <code>--pray</code> represents the future of version control &mdash; a future in which the
          tools we use reflect the reality of how we work, rather than the idealized version of how we wish we
          worked. Git was built for a world where developers understood their code. <code>--pray</code> is built for
          the world we actually live in.
        </p>

        <p className="reveal">We look forward to your feedback, your bug reports, and your prayers.</p>

        <blockquote className="reveal">
          <p>
            &ldquo;We shaped the stone to fit our hands. Now we shape our hands to fit the stone.{" "}
            <code>--pray</code> is the glove.&rdquo;
          </p>
          <p>&mdash; Internal design document, author unknown (possibly Copilot)</p>
        </blockquote>

        <GHTags tags={["git", "copilot", "merge-strategies", "faith-based-engineering", "prayer", "yolo"]} />
      </GHArticle>

      <GHFooter />
    </div>
  );
}
